version: '3.9'

services:
  develop:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./:/app
    command:
      - /bin/bash
    tty: true
    shm_size: '2gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
